In [1]:
from optiwindnet.api import WindFarmNetwork, Heuristic
import numpy as np

cables = [(None, 3, 206), (None, 5, 287), (None, 7, 406)]

substations = np.array([[696, 1063],], dtype=float)
turbines = np.array(
    [[1940, 279], [1920, 703], [1475, 696], [1839, 1250],
     [1277, 1296], [442, 1359], [737, 435], [1060, 26],
     [522, 176], [87, 35], [184, 417], [71, 878]],
    dtype=float
)
border = np.array( # vertices oriented counter-clockwise
    [[1951, 200], [1951, 1383], [386, 1383], [650, 708], [624, 678],
     [4, 1036], [4, 3], [1152, 3], [917, 819], [957, 854]],
    dtype=float)
# 'obstacles' is an optional location attribute
obstacles = [
    # - vertices oriented clockwise for each obstacle polygon
    # - obstacles must be strictly inside the extents polygon
    # - undefined behavior if obstacles and extents borders overlap
    # first obstacle
    np.array([[1540, 920], [1600, 940], [1600, 1150], [1400, 1200]]),
    # [second obstacle] ...
]

load c:\Users\amia\AppData\Local\miniconda3\envs\OptiWindNet\Lib\site-packages\ortools\.libs\zlib1.dll...
load c:\Users\amia\AppData\Local\miniconda3\envs\OptiWindNet\Lib\site-packages\ortools\.libs\abseil_dll.dll...
load c:\Users\amia\AppData\Local\miniconda3\envs\OptiWindNet\Lib\site-packages\ortools\.libs\utf8_validity.dll...
load c:\Users\amia\AppData\Local\miniconda3\envs\OptiWindNet\Lib\site-packages\ortools\.libs\re2.dll...
load c:\Users\amia\AppData\Local\miniconda3\envs\OptiWindNet\Lib\site-packages\ortools\.libs\libprotobuf.dll...
load c:\Users\amia\AppData\Local\miniconda3\envs\OptiWindNet\Lib\site-packages\ortools\.libs\highs.dll...
load c:\Users\amia\AppData\Local\miniconda3\envs\OptiWindNet\Lib\site-packages\ortools\.libs\ortools.dll...


In [4]:
wfn = WindFarmNetwork(turbines=turbines, substations=substations, border=border, obstacles=obstacles, cables=cables)

router = Heuristic(wfn=wfn, solver='EW') # default is EW
router()
grad_wt, grad_ss = router.gradient()
print('gradients_wt\n', grad_wt)
print('gradients_ss\n', grad_ss)
print()
print('cost: ', wfn.cost())

gradients_wt
 [[   9.70618904 -205.77120764]
 [ 226.44385177    5.23334324]
 [-205.97451805   -3.2400486 ]
 [ 255.86790133  180.36510604]
 [ -19.66557761  130.23903455]
 [-134.14999154  156.3322736 ]
 [  82.09097521  -22.64334569]
 [ 127.67235372 -161.66561198]
 [ -15.58364377 -340.42274323]
 [ -50.69989847 -199.66351769]
 [ -67.98698916  119.1807082 ]
 [ -49.04273777  200.07700985]]
gradients_ss
 [[-158.6779147   141.97899934]]

cost:  1438829.7308889795


In [6]:
substations = np.array([[695, 1060],], dtype=float)
router(turbines=turbines, substations=substations)
print(wfn.cost())
#print(wfn.G.graph['VertexC'][-substations.shape[0]:, :])
grad_wt, grad_ss = router.gradient()
print('gradients_wt\n', grad_wt)
print('gradients_ss\n', grad_ss)
print()
print('cost: ', wfn.cost())

1438566.1977794454
gradients_wt
 [[   9.70618904 -205.77120764]
 [ 226.44385177    5.23334324]
 [-205.97451805   -3.2400486 ]
 [ 255.86790133  180.36510604]
 [ -20.0778557   131.26138796]
 [-133.06410174  157.25757479]
 [  82.86272004  -22.5922228 ]
 [ 127.67235372 -161.66561198]
 [ -15.58364377 -340.42274323]
 [ -50.69989847 -199.66351769]
 [ -67.98698916  119.1807082 ]
 [ -49.04273777  200.07700985]]
gradients_ss
 [[-160.12327124  139.98022186]]

cost:  1438566.1977794454


In [7]:
substations = np.array([[700, 1050],], dtype=float)
grad_wt, grad_ss = router.gradient(turbines=turbines, substations=substations)
print('gradients_wt\n', grad_wt)
print('gradients_ss\n', grad_ss)
print()
print('cost: ', wfn.cost())

gradients_wt
 [[   9.70618904 -205.77120764]
 [ 226.44385177    5.23334324]
 [-205.97451805   -3.2400486 ]
 [ 255.86790133  180.36510604]
 [ -22.0362706   135.97044952]
 [-132.02893155  158.12767384]
 [  80.02284591  -22.77306745]
 [ 127.67235372 -161.66561198]
 [ -15.58364377 -340.42274323]
 [ -50.69989847 -199.66351769]
 [ -67.98698916  119.1807082 ]
 [ -49.04273777  200.07700985]]
gradients_ss
 [[-156.3601524   134.58190589]]

cost:  1436402.1337653387
